export default function getAllProducts() {
  return [
    {
      id: "001",
      slug: "coach-parker-chrome-40-bag",
      name: "Coach Parker Chrome 40 Bag",
      category: "Men's",
      price: 12_900_000,
      stock: 100,
      imageUrl: "https://id.coach.com/media/catalog/product/c/r/cr782_blk_a0_wid_1500_hei_1500.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=380&width=380&canvas=380:380",
      description: `The Parker Chrome 40 is a modern take on the classic bag. Made from premium leather, it features clean lines, a structured shape, and a signature Coach logo at the front. The interior features multiple pockets for organization and a magnetic snap closure. The bag can be carried by the top handles or worn as a backpack with the adjustable straps.`,
    },
    {
      id: "002",
      slug: "coach-willow-tote",
      name: "Coach Willow Tote",
      category: "Women's",
      price: 9_900_000,
      stock: 50,
      imageUrl: "https://id.coach.com/media/catalog/product/c/w/cw631_b4bk_a0_wid_1500_hei_1500.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=380&width=380&canvas=380:380",
      description: `The Willow Tote is a stylish and spacious bag perfect for everyday use. Made from premium leather, it features a classic design with clean lines and a structured shape. The interior features multiple pockets for organization and a magnetic snap closure. The bag can be carried by the top handles or worn as a shoulder bag with the adjustable strap.`,
    },
    {
      id: "003",
      slug: "coach-swinger-20-bag",
      name: "Coach Swinger 20 Bag",
      category: "Men's",
      price: 8_900_000,
      stock: 20,
      imageUrl: "https://id.coach.com/media/catalog/product/c/r/cr782_blk_a0_wid_1500_hei_1500.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=380&width=380&canvas=380:380",
      description: `The Swinger 20 is a stylish and versatile bag perfect for everyday use. Made from premium leather, it features a classic design with clean lines and a structured shape. The interior features multiple pockets for organization and a magnetic snap closure. The bag can be carried by the top handles or worn as a backpack with the adjustable straps.`,
    },
    {
      id: "004",
      slug: "coach-parker-signature-tote",
      name: "Coach Parker Signature Tote",
      category: "Women's",
      price: 12_900_000,
      stock: 100,
      imageUrl: "https://id.coach.com/media/catalog/product/c/r/cr676_b4cah_a0_wid_1500_hei_1500.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=380&width=380&canvas=380:380",
      description: `The Parker Signature Tote is a stylish and spacious bag perfect for everyday use. Made from premium leather, it features a classic design with clean lines and a structured shape. The interior features multiple pockets for organization and a magnetic snap closure. The bag can be carried by the top handles or worn as a shoulder bag with the adjustable strap.`,
    },
    {
      id: "005",
      slug: "coach-men-1-bag",
      name: "Coach Men 1 Bag",
      category: "Men's",
      price: 11_900_000,
      stock: 60,
      imageUrl: "https://id.coach.com/media/catalog/product/c/2/c2681_jichr_a0_wid_1500_hei_1500.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=380&width=380&canvas=380:380",
      description: `The Men 1 Bag is a modern and stylish bag perfect for daily use. Made from premium leather, it features a sleek design with clean lines and a structured shape.`,
    },
    {
      id: "006",
      slug: "coach-woman-2-bag",
      name: "Coach Woman 2 Bag",
      category: "Women's",
      price: 10_900_000,
      stock: 0,
      imageUrl: "https://id.coach.com/media/catalog/product/c/r/cr676_b4cah_a0_wid_1500_hei_1500.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=380&width=380&canvas=380:380",
      description: `The Woman 2 Bag is a chic and spacious bag ideal for any occasion. Made from premium leather, it features a timeless design with clean lines and a versatile shape.`,
    },
  ];
}

